### ISSUE TITLE
UserDefaults mus keine Menue Einträge schreiben

### ISSUE THREAD

**Issue by DHBW-AWZ-Admin** [studer-raimann/UserDefaults#14]
Whoops\Exception\ErrorException thrown with message "Cannot override final method ILIAS\GlobalScreen\Scope\MainMenu\Provider\AbstractStaticMainMenuPluginProvider::__construct()"

Stacktrace:
#2 Whoops\Exception\ErrorException in /srv/www/htdocs/studienstart-test_dev_dhbw_de/studienstart8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/src/Menu/Menu.php:23
#1 Whoops\Run:handleError in /srv/www/htdocs/studienstart-test_dev_dhbw_de/studienstart8/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0

**Comment by mstuder** [comment]
@DHBW-AWZ-Admin die Menu-Implementierung von UserDefaults wurde entfernt. Bitte kurz testen und falls ok, den Issue schliessen.
