### ISSUE TITLE
Fehler beim Bearbeiten / Erstellen einer Einstellung

### ISSUE THREAD

**Issue by DHBW-AWZ-Admin** [studer-raimann/UserDefaults#19]
Hallo Martin,

ich bekomme dieses Fehler bei dem Userdefauls -> Konfigurieren -> Bearbeiten ( bei einer EInstellung)

![Userdefaults](https://github.com/fluxapps/UserDefaults/assets/145437822/67acab4a-2f4c-4f28-a4ec-b56f517996db)

**Comment by mstuder** [comment]
Welchen Browser verwendest du? Kannst du einmal mittels Chrome testen und sicherstellen, dass du den Browsercache einmal löscht für die Seite. Falls der Fehler weiterhin besteht, bräuchte ich die Fehler, welche in der Browser-Konsole angezeigt werden.

**Comment by DHBW-AWZ-Admin** [comment]
ich habe Firefox und chrome verwendet. Cache bei chrome gelöscht und nochmal einen reload gemacht. leider keine Änderung:
![grafik](https://github.com/fluxapps/UserDefaults/assets/145437822/f6098302-4f9b-48c4-bdf5-86db46da8f57)

**Comment by mstuder** [comment]
Liebe @DHBW-AWZ-Admin 

Es müsste wie folgt aussehen. Für die weiteren Abklärungen bräuchte ich von dir den Auszug des Error-Logs der Browser-Konsole. Siehe nachfolgend:

![image](https://github.com/fluxapps/UserDefaults/assets/472326/8396eda8-7e78-4ba0-8097-0332b17c6dce)
