### ISSUE TITLE
Fehler beim Speichern der Konfiguartion bei UserDefaults

### ISSUE THREAD

**Issue by DHBW-AWZ-Admin** [studer-raimann/UserDefaults#22]
hier ist der Fehler vom logfile, wenn ich auf spreichern klicke.

[7475e] [2024-01-24 13:32:48.004981] ilias8_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 2 Undefined array key "global_roles" in /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/src/Adapters/Ui/InputElements/FluxEcoSearchInputElement/InputElement.php:60#0 /srv/www/htdocs/ilias/ilias8/Services/Init/classes/class.ilErrorHandling.php(443): Whoops\Run->handleError(2, 'Undefined array...', '/srv/www/htdocs...', 60)
#1 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/src/Adapters/Ui/InputElements/FluxEcoSearchInputElement/InputElement.php(60): ilErrorHandling->handlePreWhoops(2, 'Undefined array...', '/srv/www/htdocs...', 60)
#2 /srv/www/htdocs/ilias/ilias8/Services/Form/classes/class.ilPropertyFormGUI.php(340): srag\Plugins\UserDefaults\Adapters\Ui\InputElements\FluxEcoSearchInputElement\InputElement->setValueByArray(Array)
#3 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/src/Adapters/Api/AssignmentProcess/Facade.php(50): ilPropertyFormGUI->setValuesByPost()
#4 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/src/Adapters/Api/AssignmentProcess/Api.php(44): srag\Plugins\UserDefaults\Adapters\Api\AssignmentProcess\Facade->handleFormSubmission(Object(srag\Plugins\UserDefaults\Adapters\Api\AssignmentProcess\Requests\HandleFormSubmission))
#5 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/classes/UserSetting/class.UserSettingsGUI.php(165): srag\Plugins\UserDefaults\Adapters\Api\AssignmentProcess\Api->handleFormSubmission(Object(UserSettingsGUI), 17, Object(Closure))
#6 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/classes/UserSetting/class.UserSettingsGUI.php(103): UserSettingsGUI->update()
#7 /srv/www/htdocs/ilias/ilias8/Services/UICore/classes/class.ilCtrl.php(199): UserSettingsGUI->executeCommand()
#8 /srv/www/htdocs/ilias/ilias8/Customizing/global/plugins/Services/EventHandling/EventHook/UserDefaults/classes/class.ilUserDefaultsConfigGUI.php(64): ilCtrl->forwardCommand(Object(UserSettingsGUI))
#9 /srv/www/htdocs/ilias/ilias8/Services/Component/classes/class.ilPluginConfigGUI.php(88): ilUserDefaultsConfigGUI->performCommand('update')
#10 /srv/www/htdocs/ilias/ilias8/Services/UICore/classes/class.ilCtrl.php(199): ilPluginConfigGUI->executeCommand()
#11 /srv/www/htdocs/ilias/ilias8/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php(162): ilCtrl->forwardCommand(Object(ilUserDefaultsConfigGUI))
#12 /srv/www/htdocs/ilias/ilias8/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php(119): ilObjComponentSettingsGUI->forwardConfigGUI('ilUserDefaultsC...')
#13 /srv/www/htdocs/ilias/ilias8/Services/UICore/classes/class.ilCtrl.php(199): ilObjComponentSettingsGUI->executeCommand()
#14 /srv/www/htdocs/ilias/ilias8/Services/Administration/classes/class.ilAdministrationGUI.php(237): ilCtrl->forwardCommand(Object(ilObjComponentSettingsGUI))
#15 /srv/www/htdocs/ilias/ilias8/Services/UICore/classes/class.ilCtrl.php(199): ilAdministrationGUI->executeCommand()
#16 /srv/www/htdocs/ilias/ilias8/Services/UICore/classes/class.ilCtrl.php(174): ilCtrl->forwardCommand(Object(ilAdministrationGUI))
#17 /srv/www/htdocs/ilias/ilias8/ilias.php(24): ilCtrl->callBaseClass()
#18 {main}

**Comment by mstuder** [comment]
@DHBW-AWZ-Admin ich bräuchte wie erwähnt den Auszug der Browser-Konsole beim Bearbeiten von UserDefaults: https://github.com/fluxapps/UserDefaults/issues/19#issuecomment-1872499667

**Comment by DHBW-AWZ-Admin** [comment]
Hallo Martin, hier der Web console output 
![grafik](https://github.com/fluxapps/UserDefaults/assets/145437822/3902aff6-310b-4d45-93f8-35b9ec75f457)

**Comment by mstuder** [comment]
@DHBW-AWZ-Admin 
Ich habe ein neues ILIAS 8.8 aufgesetzt und erhalte den Fehler nicht. Kannst du bitte folgendes prüfen. Können die Dateien direkt aufgerufen werden:
![image](https://github.com/fluxapps/UserDefaults/assets/472326/57cc55f8-77cc-4c94-a7fa-fe9c84f1b671)

Habt ihr eine Firewall in Betrieb, welche .mjs-Dateien sperrt? Weitere Hinweise zu .mjs-Dateien findet ihr unter:
https://v8.dev/features/modules#mjs

**Comment by DHBW-AWZ-Admin** [comment]
danke lieber Martin für den Tipp. jetzt klappt es :-)
mjs hat in dem mime.types des webservers gefehlt
