### ISSUE TITLE
errors in UserDefaults

### ISSUE THREAD

**Issue by ingoj** [studer-raimann/UserDefaults#24]
first:
I encountered a (new) error when creating new UDF rules. OrgU Position was empty on new rules aud caused a crash. My current PR contains a way to fix this. Other approach could be to set Position initially to Employee, but this coud fail if this Position was deleted by admins.
second:
CascadingSelect had some changes. It is required, that $definition contains a key "required" (value true|false) when calling CascadingSelect.
The behaviour of getColumnDefinition changed, too, since the array for the definitions is protected now.   I worked around that by fetching the array content as JSON and decoding this.
third:
fillForm in UDFCheckGUI fetched column definitions instead of current values

My current PR (#23) should fix all this, I could test some functions of UserDefaults successfully (with still some minor flaws in cascaded values, but these may result from Cascading selet itself. Not tried: setting $definition['required'] = false may help for some)

issue #17 should be fixed by the PR.

**Comment by mstuder** [comment]
thx for this work!
